const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const GET_DOGS = "GET_DOGS";
const GET_DOG_DETAIL = "GET_DOG_DETAIL";
const GET_DOG_NAME = "GET_DOG_NAME";
const FILTER_TEMPERAMENTS = "FILTER_TEMPERAMENTS";
const FILTER_ORIGIN = "FILTER_ORIGIN";
const ORDER_ACDC = "ORDER_ACDC";
const ORDER_WEIGHT = "ORDER_WEIGHT";
const LOADING = "LOADING";

export {
  GET_TEMPERAMENTS,
  GET_DOGS,
  GET_DOG_DETAIL,
  GET_DOG_NAME,
  FILTER_TEMPERAMENTS,
  FILTER_ORIGIN,
  ORDER_ACDC,
  ORDER_WEIGHT,
  LOADING
};
